// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNd5ifg8CHZVAwPj1LUs4S09bQvvIjIf0',
    appId: '1:302169781959:web:6884af2824f3d8462530e2',
    messagingSenderId: '302169781959',
    projectId: 'budgeit-39dea',
    authDomain: 'budgeit-39dea.firebaseapp.com',
    storageBucket: 'budgeit-39dea.appspot.com',
    measurementId: 'G-WNXZG2SZ5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4r2URZKMWo8rWMxM5PKfTizR_ke8WyA',
    appId: '1:302169781959:android:118b9d9a2298112d2530e2',
    messagingSenderId: '302169781959',
    projectId: 'budgeit-39dea',
    storageBucket: 'budgeit-39dea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJS1CGDs-PosRHj5Etakaq76Co4oGdQc',
    appId: '1:302169781959:ios:8987c977e2d5c76d2530e2',
    messagingSenderId: '302169781959',
    projectId: 'budgeit-39dea',
    storageBucket: 'budgeit-39dea.appspot.com',
    iosBundleId: 'com.example.budgeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJS1CGDs-PosRHj5Etakaq76Co4oGdQc',
    appId: '1:302169781959:ios:8987c977e2d5c76d2530e2',
    messagingSenderId: '302169781959',
    projectId: 'budgeit-39dea',
    storageBucket: 'budgeit-39dea.appspot.com',
    iosBundleId: 'com.example.budgeit',
  );
}
